name: order_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_typeahead: ^5.2.0
  get_it: ^7.7.0
  http: ^1.2.1
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Public_Sans
      fonts:
        - asset: assets/fonts/Public_Sans/PublicSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Public_Sans/PublicSans-Italic.ttf
          style: italic
        - asset: assets/fonts/Public_Sans/PublicSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Public_Sans/PublicSans-Regular.ttf
        - asset: assets/fonts/Public_Sans/PublicSans-Semibold.ttf
          weight: 600
